from list_of_500_words import easy_list

words_list_1500 = (
    "acids", "admit", "adopt", "adult", "agent", "agony", "ahead", "alarm", "album", "alert",
    "alien", "alley", "allow", "alone", "along", "altar", "alter", "amend", "among", "anger",
    "angle", "angry", "ankle", "apart", "apple", "apply", "apron", "arena", "argue", "arise",
    "armed", "arrow", "aside", "asset", "atlas", "audio", "audit", "avoid", "award", "aware",
    "awful", "bacon", "badge", "bagel", "baker", "bald", "ballet", "balmy", "banjo", "barge",
    "barn", "basil", "bass", "batch", "bathe", "baths", "beach", "beads", "beard", "beast",
    "beats", "beech", "beef", "beers", "begin", "being", "below", "bench", "bible", "bikes",
    "birth", "bison", "black", "blade", "blame", "blank", "blast", "blend", "bless", "blimp",
    "blind", "blink", "bliss", "block", "blood", "bloom", "blues", "bluff", "board", "boast",
    "bogus", "boils", "bonds", "bones", "bonus", "books", "boost", "boots", "bored", "bound",
    "bowel", "boxed", "boxes", "boyle", "brace", "brady", "brake", "brand", "brass", "brave",
    "bread", "break", "brick", "bride", "brief", "bring", "brink", "brisk", "broad", "broil",
    "broke", "brook", "broth", "brown", "bruin", "brush", "brute", "bucks", "buddy",
    "build", "built", "bulge", "bulky", "bulls", "bully", "bunch", "bunny", "bureau",
    "burns", "burst", "buses", "bushy", "butch", "butts", "buyer", "cabin", "cable", "cacao",
    "cache", "cacti", "caddy", "cadet", "caged", "cages", "cagey", "cain", "cakes", "calif",
    "calls", "calms", "camel", "camps", "canal", "candy", "canoe", "canon", "caped", "capes",
    "cards", "cargo", "carlo", "carol", "carry", "carte", "carve", "cased", "cases", "caste",
    "catch", "cater", "catty", "cause", "cedar", "celeb", "cell", "cents", "cider",
    "cites", "civil", "clams", "clang", "clank", "claps", "clash", "class", "claws", "clean",
    "clear", "clerk", "click", "cliff", "climb", "clime", "cling", "clink", "clock", "close",
    "cloth", "cloud", "clout", "clown", "clubs", "clump", "coach", "coast", "coats", "cobra",
    "cocks", "cocoa", "codex", "cogent", "coils", "coins", "coked", "cokes", "colas", "colds",
    "colts", "comas", "combs", "comet", "comic", "comma", "comps", "cones", "conga",
    "conic", "cooks", "cooky", "cools", "copra", "coral", "corps", "costs", "cough", "could",
    "count", "court", "coven", "cover", "coyly", "cozen", "crack", "craft", "cramp", "crane",
    "crank", "crape", "crash", "crate", "crave", "crawl", "craze", "crazy", "cream", "credo",
    "creed", "creek", "creep", "crepe", "crest", "crew", "cribs", "crick", "cried", "crier",
    "cries", "crime", "crisp", "croak", "crock", "croft", "crone", "crony", "crook", "croon",
    "cross", "crowd", "crown", "crude", "cruel", "crumb", "crush", "crust", "crypt", "cuban",
    "cubed", "cubes", "cubic", "cuffs", "cuing", "culpa", "cumin", "cupid", "cures",
    "cure", "curls", "curly", "curry", "curse", "curve", "cushy", "cutie", "cycle", "daddy",
    "daily", "dairy", "daisy", "dally", "dance", "dandy", "danes", "dark", "darns",
    "darts", "dawns", "dealt", "dealt", "death", "debit", "debts", "debug",
    "decaf", "decry", "deeds", "deems", "deeps", "deere", "defer", "deify", "deign", "delay",
    "delhi", "delta", "demon", "dense", "dents", "depot", "depth", "derby", "deuce", "devil",
    "devoid", "dials", "diary", "dice", "dicks", "dicky", "dicta", "diets", "digs",
    "dikes", "dildo", "dill", "dime", "dine", "dingo", "dints", "dirty", "disco", "dish",
    "disks", "ditch", "ditto", "divan", "diver", "dixie", "dizzy", "docks", "dodge", "doing",
    "doled", "dolls", "dolly", "dolt", "dome", "done", "donor", "donut", "dooms", "doors",
    "doped", "dopes", "dopey", "dorks", "dorky", "dorm", "dose", "doss", "dote", "doubt",
    "dough", "douse", "dover", "doves", "downs", "dozen", "draft", "drain", "drake", "drama",
    "drank", "drape", "draws", "dread", "dream", "dregs", "dress", "drier", "drips", "drive",
    "droll", "drone", "drool", "droop", "drops", "dross", "drove", "drown", "druid", "drums",
    "drunk", "dryer", "dual", "dubs", "duck", "ducks", "dude", "duels", "duets", "duffy",
    "dukes", "dulls", "dully", "dummy", "dumps", "dunes", "dunks", "dunno", "dunno", "dupe",
    "dupes", "dusk", "dust", "dusts", "dusty", "dutch", "dying", "dykes", "eager",
    "eagle", "earls", "early", "earth", "eased", "easel", "eases", "easts", "eaten", "ebony",
    "echo", "edges", "edict", "edits", "eerie", "egged", "egret", "eider", "eight", "eject",
    "elate", "elbow", "elder", "elect", "elite", "elope", "elves", "embed", "ember", "emery",
    "emote", "empty", "enact", "ended", "endow", "enema", "enemy", "engel",
    "enjoy", "enrol", "enter", "entry", "envoy", "equal", "equip", "erase", "erect", "erode",
    "error", "erupt", "essay", "ester", "ethic", "euros", "evens", "event", "every",
    "evict", "evils", "evoke", "exalt", "excel", "exert", "exile", "exist", "exits", "expel",
    "exude", "exult", "fable", "faces", "facet", "facts", "fades", "faint", "faith", "falls",
    "false", "famed", "fancy", "fangs", "fanny", "farce", "fared", "fares", "fargo",
    "farms", "farts", "fates", "fatal", "fatty", "fault", "fawns", "fazed",
    "fazes", "fears", "feast", "fecal", "feels", "fends", "feral", "ferns",
    "ferry", "fetch", "fetus", "fever", "fewer", "ficus", "fidel", "field", "fiend",
    "fiery", "fifth", "fifty", "fight", "filed", "files", "fills", "films", "filth",
    "final", "finds", "fined", "finer", "finis", "finks", "fired", "fires", "firms", "first",
    "fish", "fists", "fiver", "fives", "fixed", "fixer", "fixes", "fizzy", "fjord", "flack",
    "flags", "flair", "flake", "flame", "flank", "flaps", "flare", "flash", "flask", "flats",
    "flaws", "flays", "fleck", "flesh", "flick", "flied", "flier", "flies", "flint", "flips",
    "flirt", "float", "flock", "flogs", "flood", "floor", "flops", "flora", "floss", "flour",
    "flout", "flows", "floyd", "flush", "flute", "flyer", "foams", "focal", "focus",
    "foils", "folds", "folio", "folks", "folly", "fonds", "fonts", "foods", "fools", "foot",
    "foots", "foray", "force", "forge", "forks", "forms", "forts", "forty", "forum", "fouls",
    "found", "fount", "foxes", "foyer", "frame", "franc", "frank", "franz",
    "frats", "fraud", "frays", "freak", "freed", "frees", "freon", "fresh", "frets",
    "friar", "fried", "fries", "frisk", "frock", "frogs", "frond", "front", "frost", "froth",
    "frown", "froze", "fruit", "fuels", "fugal", "fugue", "fully", "fumed", "fumes",
    "funds", "fungi", "funky", "funny", "furls", "furor", "furry", "furze", "fused",
    "fuses", "fussy", "futon", "fuze", "fuzes", "gains", "gamed", "games", "gamma",
    "gangs", "gaped", "gapes", "garbo", "garbs", "gases", "gassy", "gated", "gates", "gator",
    "gaudy", "gauge", "gauls", "gaunt", "gauze", "gauzy", "gavel", "gayer", "gayer",
    "gazed", "gazer", "gazes", "gecko", "geese", "genie", "genre", "genus",
    "geoff", "george", "germs", "giant", "gibbs", "giddy", "gifts", "gilds", "giles", "gills",
    "gills", "girds", "girls", "girth", "given", "gives", "glade", "glads", "glans",
    "glare", "glass", "glaze", "gleam", "glean", "glens", "glide", "glint", "glitz", "gloat",
    "globe", "globs", "gloom", "glory", "gloss", "glove", "glows", "glued", "glues", "gluey",
    "glyph", "gnarl", "gnash", "gnats", "gnaws", "goads", "goals", "goats",
    "godly", "goers", "goeth", "going", "golds", "golem", "golly", "goner", "gongs",
    "gonna", "goods", "goody", "gooey", "goofy", "goofs", "goofy", "goons", "goose", "gores",
    "gored", "gores", "gorge", "gory", "gorse", "gotta", "gouge", "gourd", "gouts", "gouty",
    "gowns", "grab", "grabs", "grace", "grad", "grads", "graft", "grain", "grams",
    "grand", "grant", "grape", "graph", "grasp", "grass", "grate", "grave", "gravy", "grays",
    "graze", "great", "grebe", "greed", "greek", "green", "greet", "grief",
    "grids", "grief", "grill", "grime", "grimy", "grind", "grins", "gripe", "grips",
    "grist", "grits", "groan", "groat", "groin", "groom", "grope", "gross", "group", "grout",
    "grove", "growl", "grown", "grows", "grubs", "gruel", "gruff", "grump", "grunt", "guano",
    "guard", "guess", "guest", "guide", "guild", "guile", "guilt", "guise", "gulfs", "gulls",
    "gully", "gumbo", "gummy", "gunny", "guppy", "gurus", "gushy", "gusts", "gusto", "gusts",
    "gusty", "gutsy", "gypsy", "gyros", "habit", "hacks", "hades", "hadst", "hafts",
    "hails", "hairy", "halos", "halve", "hands", "handy", "hangs",
    "hanky", "happy", "hardy", "harem", "harks", "harms", "harry", "harsh", "harts",
    "hash", "haste", "hasty", "hatch", "hated", "hater", "hates", "haunt", "haven",
    "haves", "havoc", "hawks", "hayed", "hazel", "hazed", "hazel", "hazel", "hazes",
    "heads", "heady", "heals", "heaps", "heard", "hears", "heart", "heath", "heats", "heave",
    "heavy", "hedge", "heeds", "heels", "hefts", "hefty", "heirs",
    "heist", "helix", "hello", "helms", "helps", "hence", "henna",
    "henry", "herbs", "herds", "heron", "hertz", "hewed", "hexed", "hexes",
    "hicks", "hides", "highs", "hiked", "hiker", "hikes", "hills", "hilly", "hinds",
    "hindu", "hinge", "hints", "hippo", "hippy", "hired", "hirer", "hires", "hitch", "hive",
    "hoard", "hoary", "hocks", "hocus", "hoist",
    "hokum", "holds", "holes", "holey", "holly", "honda", "honed", "honer", "hones",
    "honey", "honks", "hooch", "hoods", "hooks", "hoops", "hoots",
    "hoped", "hoper", "hopes", "horde", "horns", "horny", "horne", "horse", "hosed",
    "hoses", "hosts", "hotel", "hotly", "hound", "hours", "house", "hovel", "hover",
    "howdy", "howdy", "howls", "hulks", "hulls", "humid", "hunch", "hunks",
    "hunts", "hurls", "hurts", "husks", "husky", "hussy", "hutch",
    "hydra", "hydro", "hyena", "hying", "hymen", "hyper", "hypos", "iambi", "iambs", "ibex",
    "ibis", "ices", "icing", "icons", "ideal", "ideas", "idiom", "idiot", "idled", "idler",
    "idles", "idols", "igloo", "ilium", "image", "imago", "imbue", "impel", "imply",
    "inapt", "inane", "inapt", "inapt", "incas", "incur", "incus", "index", "india", "indie",
    "inept", "inert", "infer", "infix", "infra", "ingot", "inlay", "inlet", "inner", "inns",
    "inset", "intro", "inure", "iotas", "irons", "irony", "islet", "issue",
    "items", "ivied", "ivory", "jacks", "jaded", "jades", "jails", "jambs",
    "japes", "jaunt",
    "jazzy", "jeans", "jeeps", "jelly", "jerky",
    "jerks", "jerky", "jerks", "jerky", "jets", "jets", "jewel",
    "jibes", "jihad", "jingle", "joins", "joint", "joist", "joked", "joker", "jokes", "jolty",
    "joule", "joust", "jowls", "judge", "judy", "juice",
    "juicy", "juju", "juke", "jumbo", "jumps", "jumpy",
    "junky", "junta", "junto", "juror", "just", "just", "kabob", "kable", "kayak", "keeps",
    "kelpy", "kempt",
    "kerbs", "ketch",
    "khaki", "khmer", "khz", "kicks", "kicky", "kiddo", "kiddy", "kills", "kilos", "kilts", "kinds", "kinds", "kings", "kinks",
    "kinky", "kinos", "kiosk", "kippa", "kippy", "kites", "kitty", "kiwis",
    "about", "after", "again", "air", "also", "amaze", "among", "angel", "anger", "angry",
    "apple", "apply", "arena", "argue", "arise", "aside", "asset", "audio", "audit", "avoid",
    "awake", "award", "aware", "awful", "badge", "baker", "bathe", "beach", "beard", "begin",
    "being", "below", "bench", "bible", "birth", "black", "blade", "bless", "blind", "block",
    "blood", "blow", "board", "boast", "bored", "bound", "brain", "brave", "bread", "break",
    "brick", "brief", "bring", "broad", "broken", "brush", "buddy", "build", "built", "bunch",
    "buyer", "cabin", "cable", "carry", "catch", "cause", "cease", "chain", "chair", "chalk",
    "charm", "chase", "cheap", "cheat", "check", "cheek", "cheer", "chest", "chief", "child",
    "chill", "chime", "chunk", "civil", "claim", "clash", "class", "clean", "clear", "climb",
    "clock", "close", "cloth", "cloud", "coach", "coast", "color", "comic", "commit", "could",
    "count", "court", "cover", "crack", "craft", "crash", "crawl", "crazy", "cream", "crime",
    "cross", "crowd", "crown", "crush", "cure", "curve", "cycle", "dance", "dare", "dark",
    "death", "debit", "debut", "decaf", "decoy", "decor", "decoy", "decoy", "deity", "delay",
    "debut", "decaf", "decoy", "decoy", "decoy", "decoy", "delta", "demon", "depth", "diary",
    "digit", "diner", "ditch", "diver", "divine", "dodge", "doing", "doubt", "draft", "drain",
    "draw", "dream", "dress", "drink", "drive", "drown", "drunk", "dying", "eager", "eagle",
    "early", "earth", "eight", "elbow", "elder", "elect", "elite", "email", "embrace", "employ",
    "empty", "enemy", "enjoy", "enter", "entry", "equal", "error", "essay", "event", "every",
    "exact", "exist", "extra", "faith", "false", "fancy", "fatal", "fault", "feast",
    "fifth", "fight", "final", "first", "fixed", "flame", "flash", "flask", "fleet", "flesh",
    "flock", "floor", "flour", "fluid", "focal", "focus", "foggy", "force", "forge", "forget",
    "fought", "found", "frame", "frank", "fraud", "freak", "freed", "fresh", "front", "frown",
    "fruit", "fully", "funny", "gains", "gamma", "genre", "giant", "given", "glory",
    "glove", "going", "grace", "grain", "grand", "grape", "grass", "great", "green", "greet",
    "grind", "grove", "guard", "guest", "guide", "habit", "happy", "hardy", "haste", "hatch",
    "haunt", "hears", "heart", "heave", "hefty", "hello", "hence", "honey", "horse",
    "hotel", "house", "human", "hurry", "ideal", "image", "imply", "index", "inner",
    "input", "inset", "intel", "irony", "issue", "joint", "joker", "judge", "juice", "knead",
    "knife", "knock", "label", "laser", "later", "laugh", "layer", "least", "leave",
    "legal", "level", "light", "limit", "lingo", "lived", "liver", "lobby", "local", "logic",
    "loose", "lotus", "lover", "lower", "lucid", "lunch", "lunar", "magic", "major", "maker",
    "march", "match", "might", "milky", "mince", "minor", "misty", "mixer", "model", "moral",
    "motor", "mouse", "mouth", "movie", "music", "myth", "naked", "named", "nasal", "nasty",
    "naval", "nerve", "never", "niche", "night", "noble", "noise", "nomad", "north", "novel",
    "nurse", "oasis", "occur", "ocean", "offer", "often", "olive", "onset", "optic", "order",
    "organ", "other", "outer", "owner", "panel", "panic", "pants", "paper", "party", "peace",
    "pearl", "penal", "phase", "phone", "photo", "piano", "pilot", "pitch", "pizza", "place",
    "plain", "plant", "plaza", "point", "polar", "polka", "power", "pride", "prime", "print",
    "prior", "prize", "proof", "proud", "punch", "purse", "queen", "quiet", "quite", "quote",
    "rally", "range", "rapid", "ratio", "reach", "react", "ready", "refer", "relay", "relax",
    "reply", "rhyme", "rider", "ridge", "right", "rigid", "rival", "river", "roast", "robot",
    "rocky", "royal", "ruler", "saint", "salty", "sauce", "sauna", "savor", "scale", "scare",
    "scene", "scope", "score", "scout", "scrap", "screw", "script", "seize", "sense", "serve",
    "seven", "shade", "shake", "shall", "shape", "share", "sharp", "sheep", "sheet", "shelf",
    "shine", "shirt", "shock", "shoot", "short", "shout", "silly", "since", "siren", "skate",
    "skull", "slave", "sleep", "slice", "slide", "slime", "slope", "small", "smart", "smell",
    "smile", "smoke", "snake", "snack", "sneak", "sneer", "solar", "solid", "solve", "sound",
    "space", "spare", "speak", "speed", "spice", "spill", "spine", "split", "spoil", "sport",
    "spray", "spree", "staff", "stage", "stain", "stake", "stall", "stamp", "stand", "stare",
    "start", "state", "steak", "steal", "steam", "steep", "stern", "stick", "sting", "stock",
    "stone", "stool", "stoop", "store", "storm", "story", "stove", "strap", "straw", "strip",
    "study", "stuff", "style", "sugar", "suite", "super", "swarm", "sweet", "swift", "sword",
    "table", "taste", "teach", "tease", "teeth", "tense", "thank", "thick", "think", "thorn",
    "those", "three", "throb", "throw", "thumb", "tight", "timer", "toast", "today", "token",
    "tonic", "toxic", "trace", "track", "trade", "trail", "train", "trait", "trash", "tread",
    "treat", "trend", "trick", "troop", "truce", "truly", "trunk", "trust", "truth", "twist",
    "ultra", "under", "union", "unity", "until", "upper", "upset", "usage", "usual", "utter",
    "value", "vapor", "video", "vigil", "vivid", "vocal", "voice", "voter", "vowel", "waste",
    "watch", "water", "weary", "wedge", "weird", "whale", "wheat", "wheel", "where", "which",
    "while", "white", "whole", "whose", "widen", "widow", "width", "wild", "will", "wind",
    "wine", "wing", "wipe", "wire", "wise", "wish", "with", "wolf", "wood", "word", "work",
    "worm", "worn", "wrap", "wrist", "wrong", "yield", "young", "youth", "zebra", "zesty",
    "zinc", "zone", "zoo", "about", "after", "again", "air", "also", "amaze", "among", "angel", "anger", "angry",
    "apple", "apply", "arena", "argue", "arise", "aside", "asset", "audio", "audit", "avoid",
    "awake", "award", "aware", "awful", "badge", "baker", "bathe", "beach", "beard", "begin",
    "being", "below", "bench", "bible", "birth", "black", "blade", "bless", "blind", "block",
    "blood", "blow", "board", "boast", "bored", "bound", "brain", "brave", "bread", "break",
    "brick", "brief", "bring", "broad", "broken", "brush", "buddy", "build", "built", "bunch",
    "buyer", "cabin", "cable", "carry", "catch", "cause", "cease", "chain", "chair", "chalk",
    "charm", "chase", "cheap", "cheat", "check", "cheek", "cheer", "chest", "chief", "child",
    "chill", "chime", "chunk", "civil", "claim", "clash", "class", "clean", "clear", "climb",
    "clock", "close", "cloth", "cloud", "coach", "coast", "color", "comic", "commit", "could",
    "count", "court", "cover", "crack", "craft", "crash", "crawl", "crazy", "cream", "crime",
    "cross", "crowd", "crown", "crush", "cure", "curve", "cycle", "dance", "dare", "dark",
    "death", "debit", "debut", "decaf", "decoy", "decor", "decoy", "decoy", "deity", "delay",
    "debut", "decaf", "decoy", "decoy", "decoy", "decoy", "delta", "demon", "depth", "diary",
    "digit", "diner", "ditch", "diver", "divine", "dodge", "doing", "doubt", "draft", "drain",
    "draw", "dream", "dress", "drink", "drive", "drown", "drunk", "dying", "eager", "eagle",
    "early", "earth", "eight", "elbow", "elder", "elect", "elite", "email", "embrace", "employ",
    "empty", "enemy", "enjoy", "enter", "entry", "equal", "error", "essay", "event", "every",
    "exact", "exist", "extra", "faith", "false", "fancy", "fatal", "fault", "favor", "feast",
    "fifth", "fight", "final", "first", "fixed", "flame", "flash", "flask", "fleet", "flesh",
    "flock", "floor", "flour", "fluid", "focal", "focus", "foggy", "force", "forge", "forget",
    "fought", "found", "frame", "frank", "fraud", "freak", "freed", "fresh", "front", "frown",
    "fruit", "fully", "funny", "gains", "galax", "gamma", "genre", "giant", "given", "glory",
    "glove", "going", "grace", "grain", "grand", "grape", "grass", "great", "green", "greet",
    "grind", "grove", "guard", "guest", "guide", "habit", "happy", "hardy", "haste", "hatch",
    "haunt", "hears", "heart", "heave", "hefty", "hello", "hence", "honey", "honor", "horse",
    "hotel", "house", "human", "humor", "hurry", "ideal", "image", "imply", "index", "inner",
    "input", "inset", "intel", "irony", "issue", "joint", "joker", "judge", "juice", "knead",
    "knife", "knock", "label", "labor", "laser", "later", "laugh", "layer", "least", "leave",
    "legal", "level", "light", "limit", "lingo", "lived", "liver", "lobby", "local", "logic",
    "loose", "lotus", "lover", "lower", "lucid", "lunch", "lunar", "magic", "major", "maker",
    "march", "match", "might", "milky", "mince", "minor", "misty", "mixer", "model", "moral",
    "motor", "mouse", "mouth", "movie", "music", "myth", "naked", "named", "nasal", "nasty",
    "naval", "nerve", "never", "niche", "night", "noble", "noise", "nomad", "north", "novel",
    "nurse", "oasis", "occur", "ocean", "offer", "often", "olive", "onset", "optic", "order",
    "organ", "other", "outer", "owner", "panel", "panic", "pants", "paper", "party", "peace",
    "pearl", "penal", "phase", "phone", "photo", "piano", "pilot", "pitch", "pizza", "place",
    "plain", "plant", "plaza", "point", "polar", "polka", "power", "pride", "prime", "print",
    "prior", "prize", "proof", "proud", "punch", "purse", "queen", "quiet", "quite", "quote",
    "rally", "range", "rapid", "ratio", "reach", "react", "ready", "refer", "relay", "relax",
    "reply", "rhyme", "rider", "ridge", "right", "rigid", "rival", "river", "roast", "robot",
    "rocky", "royal", "ruler", "saint", "salty", "sauce", "sauna", "savor", "scale", "scare",
    "scene", "scope", "score", "scout", "scrap", "screw", "script", "seize", "sense", "serve",
    "seven", "shade", "shake", "shall", "shape", "share", "sharp", "sheep", "sheet", "shelf",
    "shine", "shirt", "shock", "shoot", "short", "shout", "silly", "since", "siren", "skate",
    "skull", "slave", "sleep", "slice", "slide", "slime", "slope", "small", "smart", "smell",
    "smile", "smoke", "snake", "snack", "sneak", "sneer", "solar", "solid", "solve", "sound",
    "space", "spare", "speak", "speed", "spice", "spill", "spine", "split", "spoil", "sport",
    "spray", "spree", "staff", "stage", "stain", "stake", "stall", "stamp", "stand", "stare",
    "start", "state", "steak", "steal", "steam", "steep", "stern", "stick", "sting", "stock",
    "stone", "stool", "stoop", "store", "storm", "story", "stove", "strap", "straw", "strip",
    "study", "stuff", "style", "sugar", "suite", "super", "swarm", "sweet", "swift", "sword",
    "table", "taste", "teach", "tease", "teeth", "tense", "thank", "thick", "think", "thorn",
    "those", "three", "throb", "throw", "thumb", "tight", "timer", "toast", "today", "token",
    "tonic", "toxic", "trace", "track", "trade", "trail", "train", "trait", "trash", "tread",
    "treat", "trend", "trick", "troop", "truce", "truly", "trunk", "trust", "truth", "twist",
    "ultra", "under", "union", "unity", "until", "upper", "upset", "usage", "usual", "utter",
    "value", "vapor", "video", "vigil", "vivid", "vocal", "voice", "voter", "vowel", "waste",
    "watch", "water", "weary", "wedge", "weird", "whale", "wheat", "wheel", "where", "which",
    "while", "white", "whole", "whose", "widen", "widow", "width", "wild", "will", "wind",
    "wine", "wing", "wipe", "wire", "wise", "wish", "with", "wolf", "wood", "word", "work",
    "worm", "worn", "wrap", "wrist", "wrong", "yield", "young", "youth", "zebra", "zesty",
    "zinc", "zone", "zoo",
)

new_list_1500 = list(set(words_list_1500))

real_list_1500 = []

for i in new_list_1500:
    if len(i) == 5:
        real_list_1500.append(i)

#1474 words

set_1500 = set(real_list_1500)
set_500 = set(easy_list)

hard_set = set_1500.difference(set_500)

hard_list = list(hard_set)
hard_list.sort()


#897 words remaining
