words_list_500 = [
    "about", "after", "again", "amaze", "among", "angel", "anger", "angry",
    "apple", "apply", "arena", "argue", "arise", "aside", "asset", "audio", "audit", "avoid",
    "awake", "award", "aware", "awful", "badge", "baker", "bathe", "beach", "beard", "begin",
    "being", "below", "bench", "bible", "birth", "black", "blade", "bless", "blind", "block",
    "blood", "blow", "board", "boast", "bored", "bound", "brain", "brave", "bread", "break",
    "brick", "brief", "bring", "broad", "broken", "brush", "buddy", "build", "built", "bunch",
    "buyer", "cabin", "cable", "carry", "catch", "cause", "cease", "chain", "chair", "chalk",
    "charm", "chase", "cheap", "cheat", "check", "cheek", "cheer", "chest", "chief", "child",
    "chill", "chime", "chunk", "civil", "claim", "clash", "class", "clean", "clear", "climb",
    "clock", "close", "cloth", "cloud", "coach", "coast", "color", "comic", "commit", "could",
    "count", "court", "cover", "crack", "craft", "crash", "crawl", "crazy", "cream", "crime",
    "cross", "crowd", "crown", "crush", "cure", "curve", "cycle", "dance",
    "death", "debit", "debut", "decaf", "decoy", "decor", "decoy", "decoy", "deity", "delay",
    "debut", "decaf", "decoy", "decoy", "decoy", "decoy", "delta", "demon", "depth", "diary",
    "digit", "diner", "ditch", "diver", "divine", "dodge", "doing", "doubt", "draft", "drain", "dream", "dress", "drink", "drive", "drown", "drunk", "dying", "eager", "eagle",
    "early", "earth", "eight", "elbow", "elder", "elect", "elite", "email", "embrace", "employ",
    "empty", "enemy", "enjoy", "enter", "entry", "equal", "error", "essay", "event", "every",
    "exact", "exist", "extra", "faith", "false", "fancy", "fatal", "fault", "favor", "feast",
    "fifth", "fight", "final", "first", "fixed", "flame", "flash", "flask", "fleet", "flesh",
    "flock", "floor", "flour", "fluid", "focal", "focus", "foggy", "force", "forge", "found", "frame", "frank", "fraud", "freak", "freed", "fresh", "front", "frown",
    "fruit", "fully", "funny", "gains", "galax", "gamma", "genre", "giant", "given", "glory",
    "glove", "going", "grace", "grain", "grand", "grape", "grass", "great", "green", "greet",
    "grind", "grove", "guard", "guest", "guide", "habit", "happy", "hardy", "haste", "hatch",
    "haunt", "hears", "heart", "heave", "hefty", "hello", "hence", "honey", "honor", "horse",
    "hotel", "house", "human", "humor", "hurry", "ideal", "image", "imply", "index", "inner",
    "input", "inset", "intel", "irony", "issue", "joint", "joker", "judge", "juice", "knead",
    "knife", "knock", "label", "laser", "later", "laugh", "layer", "least", "leave",
    "legal", "level", "light", "limit", "lingo", "lived", "liver", "lobby", "local", "logic",
    "loose", "lotus", "lover", "lower", "lucid", "lunch", "lunar", "magic", "major", "maker",
    "march", "match", "might", "milky", "mince", "minor", "misty", "mixer", "model", "moral",
    "motor", "mouse", "mouth", "movie", "music", "myth", "naked", "named", "nasal", "nasty",
    "naval", "nerve", "never", "niche", "night", "noble", "noise", "nomad", "north", "novel",
    "nurse", "oasis", "occur", "ocean", "offer", "often", "olive", "onset", "optic", "order",
    "organ", "other", "outer", "owner", "panel", "panic", "pants", "paper", "party", "peace",
    "pearl", "penal", "phase", "phone", "photo", "piano", "pilot", "pitch", "pizza", "place",
    "plain", "plant", "plaza", "point", "polar", "polka", "power", "pride", "prime", "print",
    "prior", "prize", "proof", "proud", "punch", "purse", "queen", "quiet", "quite", "quote",
    "rally", "range", "rapid", "ratio", "reach", "react", "ready", "refer", "relay", "relax",
    "reply", "rhyme", "rider", "ridge", "right", "rigid", "rival", "river", "roast", "robot",
    "rocky", "royal", "ruler", "saint", "salty", "sauce", "sauna", "savor", "scale", "scare",
    "scene", "scope", "score", "scout", "scrap", "screw", "screw", "script", "screw", "screw",
    "screw", "screw", "seize", "sense", "serve", "seven", "shade", "shake", "shall", "shape",
    "share", "sharp", "sheep", "sheet", "shelf", "shine", "shirt", "shock", "shoot", "short",
    "shout", "silly", "since", "siren", "skate", "skull", "slave", "sleep", "slice", "slide",
    "slime", "slope", "small", "smart", "smell", "smile", "smoke", "snake", "snack", "sneak",
    "sneer", "solar", "solid", "solve", "sound", "space", "spare", "speak", "speed", "spice",
    "spill", "spine", "split", "spoil", "sport", "spray", "spree", "spoil", "spoil", "spoil",
    "spoil", "staff", "stage", "stain", "stake", "stall", "stamp", "stand", "stare", "start",
    "state", "steak", "steal", "steam", "steep", "stern", "stick", "sting", "stock", "stone",
    "stool", "stoop", "store", "storm", "story", "stove", "strap", "straw", "strip", "study",
    "stuff", "style", "sugar", "suite", "super", "swarm", "sweet", "swift", "sword", "table",
    "taste", "teach", "tease", "teeth", "tense", "thank", "thick", "think", "thorn", "those",
    "three", "throb", "throw", "thumb", "tight", "timer", "toast", "today", "token", "tonic",
    "toxic", "trace", "track", "trade", "trail", "train", "trait", "trash", "tread", "treat",
    "trend", "trick", "troop", "truce", "truly", "trunk", "trust", "truth", "twist", "ultra",
    "under", "union", "unity", "until", "upper", "upset", "usage", "usual", "utter", "value",
    "vapor", "video", "vigil", "vivid", "vocal", "voice", "voter", "vowel", "waste", "watch",
    "water", "weary", "wedge", "weird", "whale", "wheat", "wheel", "where", "which", "while",
    "white", "whole", "whose", "widen", "widow", "width" "wrist", "wrong", "yield", "young", "youth", "zebra", "zesty"
]

new_list_500 = list(set(words_list_500))

easy_list = []

for i in new_list_500:
    if len(i) == 5:
        easy_list.append(i)

#577 words
